### PR TITLE
Fix crash when profiling without performancemonitor resource

### PR DESCRIPTION
**Pull request by mparnaudeau**
Using gcc profiling feature (with option -pg) relies on events obtained
thanks to the performancemonitor resource that is not available on all
machines, on which that caused a crash trying to use profiling.
This fix was done in newlib but not in clib2 yet.

### CODE REVIEW

**Comment by sodero** [comment]
Thanks! But can you do the PR for the 'main' branch instead? That's the branch used in adtools.

**Comment by sodero** [comment]
Ah, now everything on 'master' was included as well. You need to rebase your 'fix_crash_pro...' branch on 'main' so that only the changes in 'library/profile_profil.c' are included.

**Comment by mparnaudeau** [comment]
Yes, I found the option in "Edit" for the pull request and that did all the mess, sorry.

**Comment by mparnaudeau** [comment]
Closed ... too many conflicts

**Comment by sodero** [comment]
No problem at all. Merged the new PR. Thanks!

**Pull request closed without merging**
